services:
  yuzu-room:
    image: k4rian/yuzu-room:latest
    container_name: yuzu-room
    hostname: yuzu-room
    volumes:
      - data:/home/yuzu
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - yuzu-room.env
    secrets:
      - yuzuroom
    ports:
      - 24872:24872/tcp
      - 24872:24872/udp
    restart: unless-stopped

volumes:
  data:

secrets:
  yuzuroom:
    file: ./secret.txt